import { TTransaction } from "@/src/shared/api/models"

export const __transactions__: TTransaction[] = [
    {
        id: 1,
        description: "за работы",
        date: "2022-04-12",
        opearation: "incomming",
        currency: 1,
        category: 1,
        amount: 10000,
        state: "done",
    },
    {
        id: 2,
        description: "за пиво",
        date: "2022-04-12",
        opearation: "incomming",
        currency: 1,
        category: 2,
        amount: 1500,
        state: "done",
    },
    {
        id: 3,
        description: "покупка 1",
        date: "2022-04-12",
        opearation: "outgouing",
        currency: 1,
        category: 1,
        amount: -3000,
        state: "done",
    },
    {
        id: 4,
        description: "покупка 2",
        date: "2022-04-12",
        opearation: "outgouing",
        currency: 1,
        category: 2,
        amount: -2000,
        state: "done",
    },
    {
        id: 5,
        description: "покупка 3",
        date: "2022-04-12",
        opearation: "outgouing",
        currency: 1,
        category: 3,
        amount: -1000,
        state: "done",
    },
    {
        id: 6,
        description: "просто так",
        date: "2022-04-12",
        opearation: "incomming",
        currency: 1,
        category: 2,
        amount: 750,
        state: "done",
    },
]
